# Generated by Django 3.0.5 on 2024-05-25 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='difficulty_rating',
        ),
    ]
