# Generated by Django 3.0.5 on 2024-03-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_userresponse_selected_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='time_spent',
            field=models.PositiveIntegerField(),
        ),
    ]
