# Generated by Django 3.0.5 on 2024-03-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20240309_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='time_spent',
            field=models.DurationField(),
        ),
    ]
