# Generated by Django 3.0.5 on 2024-04-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20240311_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='is_current_selected',
            field=models.BooleanField(default=False),
        ),
    ]
