# Generated by Django 3.0.5 on 2024-05-23 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_option_is_current_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='is_current_selected',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Option'),
        ),
    ]
