# Generated by Django 3.0.5 on 2024-05-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20240523_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='selected_option',
        ),
        migrations.AddField(
            model_name='option',
            name='is_current_selected',
            field=models.BooleanField(default=False),
        ),
    ]
