# Generated by Django 3.0.5 on 2024-05-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_userresponse_is_answered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='is_answered',
        ),
        migrations.AddField(
            model_name='question',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
    ]
