# Generated by Django 3.0.5 on 2024-05-26 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20240523_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresponse',
            old_name='difficulty_rating',
            new_name='user_confidence',
        ),
    ]
